### ISSUE TITLE
Comentário classe PedidoVenda

### ISSUE THREAD

**Issue by profRenatoOliveira1** [CLOUDYURI9/projeto-2sem#1]
Yuri, na classe PedidoVenda, você esqueceu de alterar o comentário do construtor.

/**
     * Construtor da classe Carro
     * 
     * @param  idCarro Identificador do carro
     * @param idCliente Identificador do cliente
     * @param dataPedido Data do pedido do carro
     * @param valorPedido Valor do carro pedido 
     */

**Comment by profRenatoOliveira1** [comment]
Na classe Cliente também

 /**
     * Define o cpf do cliente.
     *
     * @param cpf - O nome do modelo do carro.
     */
    public setCpf(cpf: string): void {
        this.cpf = cpf;
    }

**Comment by CLOUDYURI9** [comment]
modificações feitas

**Comment by profRenatoOliveira1** [comment]
Yuri, só mais uma modificação, o comentário da classe está

```
/**
 * Classe que representa um carro.
 */
```

Considere colocar algo parecido com o comentário abaixo para ficar mais coerente com a função da classe
```
/**
 * Classe que representa um pedido de venda de um carro.
 */

```

**Comment by CLOUDYURI9** [comment]
Comentarios modificados, tudo arrumado.

**Comment by profRenatoOliveira1** [comment]
Muito bom.
