### ISSUE TITLE
Comentários

### ISSUE THREAD

**Issue by profRenatoOliveira1** [CLOUDYURI9/projeto-2sem#2]
Yuri, fazer os comentários dos métodos de listagem, das classes e métodos do controller.

Não se esqueça de seguir o padrão /* */ e deixar bem claro o objeto das classes, dos métodos, atributos e parâmetros .

**Comment by CLOUDYURI9** [comment]
Pronto, tudo certo, comentários adicionados nas classes de listagens e model.
